# .github/workflows/create-release.yml
name: Create Racing Game Release

permissions:
    contents: write

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    build-and-release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"

            - name: Install Root Dependencies
              run: npm ci

            - name: Build Phaser Game
              run: npm run build

            - name: Create Release Package
              run: |
                  mkdir release-package
                  cp -r server/ release-package/
                  cp -r dist/ release-package/dist/
                  cp ecosystem.config.js release-package/
                  cd release-package/server
                  npm install --production

            - name: Create Zip Archive
              run: zip -r release.zip ./release-package

            - name: Create GitHub Release
              id: create_release
              uses: softprops/action-gh-release@v2
              with:
                  name: Release ${{ github.ref_name }}
                  body: |
                      ## Changes in this release
                      **Full changelog:** [here](https://github.com/milesmfe/racing-game/compare/${{ github.ref.name }}...${{ github.sha }})
                  files: release.zip
                  prerelease: ${{ endsWith(github.ref_name, '-alpha') || endsWith(github.ref_name, '-beta') }}

            - name: Notify Deployment Server
              run: |
                  # Construct the direct download URL for the asset
                  ASSET_URL="https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/release.zip"

                  # Send the URL to webhook endpoint
                  curl -X POST \
                  -H "Content-Type: application/json" \
                  -H "X-Hook-Secret: ${{ secrets.WEBHOOK_SECRET }}" \
                  -d "{\"release_url\": \"$ASSET_URL\"}" \
                  "${{ secrets.WEBHOOK_URL }}"
